version: '3'
services:
  hestiacp:
    build: .
    ports:
      - "8083:8083"
    volumes:
      - ./hestiacp:/var/www/hestiacp
    depends_on:
      - db
    environment:
      - HESTIA_DB_HOST=db
      - HESTIA_DB_USER=root
      - HESTIA_DB_PASSWORD=password
      - HESTIA_DB_NAME=hestia

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=hestia
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    volumes:
      - ./mysql:/var/lib/mysql